### ISSUE TITLE
Not working in Firefox or Chrome

### ISSUE THREAD

**Issue by aussiehash** [peli-pro/shamir_backup_wallet_recovery_for_SLIP39#1]
when I load https://iancoleman.io/bip39/
and paste in the developer console : 
bitcoinjs.bitcoin.HDNode.fromSeedHex("77d6dc4c820ca1c8d402cad5467630f9").toBase58();

I have the error :  bitcoinjs is not defined

**Comment by peli-pro** [comment]
Unfortunately bitcoinjs removed HDNode so this is not working any more. I updated the readme to use the bip32 javascript library directly. This should work.
